name: e_commerce_app
description: "E-Commerce_App"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.2.0
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.2.1
  skeletonizer: ^1.4.3
  intl: ^0.20.2
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  flutter_snake_navigationbar: ^0.6.1
  go_router: ^16.1.0
  slide_countdown: ^2.0.2
  typewritertext: ^3.0.9
  modal_bottom_sheet: ^3.0.0
  share_plus: ^11.1.0
  url_launcher: ^6.3.2
#  import_sorter: ^4.6.0 => for initialization ( flutter pub run import_sorter:main )

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/
     - assets/cardpics/
     - assets/categories_icons/
     - assets/mock_pics/
     - assets/no_data/
     - assets/logo/
     - assets/help_support/

#  fonts:
#     - family: MyFlutterApp
#       fonts:
#         - asset: assets/fonts/MyFlutterApp.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
